[build]
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "https://docs.openservicemesh.io/"
  to = "https://docs.openservicemesh.io/docs/"
